
## Implementation of matrix representation, bag of word model, count vectorizer, tfIdf vectorizer, cosine similarity

# CountVectorizer

In [ ]:
import pandas as pd
import nltk

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
a = CountVectorizer(stop_words='english')
X = ["Computers can analyze text",
     "They do it using vectors and matrices",
     "Computers can process massive amounts of text data"]
x_vect = a.fit_transform(x)
print(x_vect)
print(x_vect.todense())
print(a.vocabulary_)

  (0, 1)	1
  (0, 0)	1
  (0, 6)	1
  (1, 7)	1
  (1, 8)	1
  (1, 4)	1
  (2, 1)	1
  (2, 6)	1
  (2, 5)	1
  (2, 3)	1
  (2, 2)	1
[[1 1 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 1 1]
 [0 1 1 1 0 1 1 0 0]]
{'computer': 1, 'analyze': 0, 'text': 6, 'using': 7, 'vexters': 8, 'matriices': 4, 'processes': 5, 'massive': 3, 'data': 2}


In [ ]:
sentences = ["We are reading about Natural Language Processing Here",
            "Natural Language Processing making computers comprehend language data",
            "The field of Natural Language Processing is evolving everyday"]

sentences = [i.lower() for i in sentences]

In [ ]:
import pandas
import nltk
nltk.download('stopwords')
nltk.download('omw-1.4')
nltk.download('wordnet')
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer,SnowballStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [ ]:
import pandas
corpus = pd.Series(sentences).astype(str)

In [ ]:
def text_clean(text,keep_list):
  cleaned_text = pd.Series()
  for row in text:
    te = []
    for j in row.split():
      if j not in keep_list:
        p1 = re.sub(pattern='[^a-zA-Z0-9]',repl=' ',string = j)
        p1 = p1.lower()
        te.append(p1)
      else:
        te.append(j)
    cleaned_text = cleaned_text.append(pd.Series(" ".join(te)))
  return cleaned_text

In [ ]:
def stopwords_removal(text):
  wh_words = ['who', 'what', 'when', 'why', 'how', 'which', 'where', 'whom']
  stop_words = set(stopwords.words('english'))
  for i in wh_words:
    stop_words.remove(i)

  new_text = pd.Series()
  te1 = []
  for row in text:
    te = []
    for word in row.split():
        if(word not in stop_words):
          te.append(word)
    new_text = new_text.append(pd.Series(' '.join(te)))
    #new_text = new_text.append(pd.Series(" ".join(te)))

  #print(new_text)
  return new_text

In [ ]:
def preprocessing(text, keep_list, cleanning=True, stemi=False, stem_type=None, lemmatiz=False, removal_stopwords = False):

  if cleanning == True:
    text = text_clean(text,keep_list)
  print("ho")
  if removal_stopwords==True:
    text = stopwords_removal(text)
  else:
    text = [[x for x in x.split()] for x in text]
  print("ho")
  if lemmatiz == True:
    text = lemmatization(text)
  print("ho")
  if stemi == True:
    text = stemming(text,stem_type)
  text = [''.join(i) for i in text]
  return text

In [ ]:
keep_list=[]
preprocessed_corpus = preprocessing(corpus,keep_list,lemmatiz =False,removal_stopwords=True)
print(preprocessed_corpus)

ho
ho
ho
['reading natural language processing', 'natural language processing making computers comprehend language data', 'field natural language processing evolving everyday']


<ipython-input-15-b0bdc0c10fc9>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  cleaned_text = pd.Series()
<ipython-input-16-77b5a8ae4c58>:7: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  new_text = pd.Series()


In [ ]:
li = []
import numpy as np
for i in preprocessed_corpus:
  for j in i.split():
    if j not in li:
      li.append(j)
li = np.sort(li)
print("Unique item ",li)
iteration = []
for i in li:
  count = 0
  for j in preprocessed_corpus:
    for k in j.split():
      if i == k:
        count = count + 1
  iteration.append(count)



li = np.array(li)
iteration = np.array(iteration)
print("Unique item with there count")
print(np.concatenate((li.reshape(len(li),1),iteration.reshape(len(iteration),1)),1))

Unique item  ['comprehend' 'computers' 'data' 'everyday' 'evolving' 'field' 'language'
 'making' 'natural' 'processing' 'reading']
Unique item with there count
[['comprehend' '1']
 ['computers' '1']
 ['data' '1']
 ['everyday' '1']
 ['evolving' '1']
 ['field' '1']
 ['language' '4']
 ['making' '1']
 ['natural' '3']
 ['processing' '3']
 ['reading' '1']]


In [ ]:
vect = {}

for i,j in enumerate(li):
  vect[j]=i
print(vect)
len(vect)

{'comprehend': 0, 'computers': 1, 'data': 2, 'everyday': 3, 'evolving': 4, 'field': 5, 'language': 6, 'making': 7, 'natural': 8, 'processing': 9, 'reading': 10}


11

In [ ]:
alpha1 = np.zeros((len(sentences),len(vect)))
print(alpha1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
vect['data']

2

In [ ]:
alpha3 = []

li = list(li)
count = 0
while(count<len(sentences)):
  temp = []
  for i in vect:
    if i in sentences[count]:
      temp.append(1)
    else:
      temp.append(0)
  count = count + 1
  alpha3.append(temp)

alpha3 = np.array(alpha3)
print(alpha3)

[[0 0 0 0 0 0 1 0 1 1 1]
 [1 1 1 0 0 0 1 1 1 1 0]
 [0 0 0 1 1 1 1 0 1 1 0]]


In [ ]:
for i,j in enumerate(sentences):
  for k in j.split():
    if k in vect:
      l = vect[k]
      alpha1[i][l] = 1
print(alpha1)

[[0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0.]]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
alpha2 = vectorizer.fit_transform(preprocessed_corpus)
print(alpha2.todense())

[[0 0 0 0 0 0 1 0 1 1 1]
 [1 1 1 0 0 0 2 1 1 1 0]
 [0 0 0 1 1 1 1 0 1 1 0]]


In [ ]:
print(sorted(vectorizer.vocabulary_.items()))
print(vect)

[('comprehend', 0), ('computers', 1), ('data', 2), ('everyday', 3), ('evolving', 4), ('field', 5), ('language', 6), ('making', 7), ('natural', 8), ('processing', 9), ('reading', 10)]
{'comprehend': 0, 'computers': 1, 'data': 2, 'everyday': 3, 'evolving': 4, 'field': 5, 'language': 6, 'making': 7, 'natural': 8, 'processing': 9, 'reading': 10}


In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
stoplist = stopwords.words('english')
text = '''
We are reading about Natural Language Processing Here,
Natural Language Processing making computers comprehend language data
The field of Natural Language Processing is evolving everyday
'''
print("\nOriginal string:")
print(text)
clean_word_list = [word for word in text.split() if word not in stoplist]
print("\nAfter removing stop words from the said text:")
print(clean_word_list)


Original string:

We are reading about Natural Language Processing Here,
Natural Language Processing making computers comprehend language data
The field of Natural Language Processing is evolving everyday


After removing stop words from the said text:
['We', 'reading', 'Natural', 'Language', 'Processing', 'Here,', 'Natural', 'Language', 'Processing', 'making', 'computers', 'comprehend', 'language', 'data', 'The', 'field', 'Natural', 'Language', 'Processing', 'evolving', 'everyday']


In [ ]:
import nltk
from nltk.corpus import stopwords

In [ ]:
txt_corpus = ["We are reading about Natural Language Processing Here",
            "Natural Language Processing making computers comprehend language data",
            "The field of Natural Language Processing is evolving everyday"]
stoplist = set('for a of the and to in on of to are at'.split(' '))
processed_text = [[word for word in document.lower().split() if word not in stoplist]for document in txt_corpus]
print(processed_text)

[['we', 'reading', 'about', 'natural', 'language', 'processing', 'here'], ['natural', 'language', 'processing', 'making', 'computers', 'comprehend', 'language', 'data'], ['field', 'natural', 'language', 'processing', 'is', 'evolving', 'everyday']]
